### ISSUE TITLE
[TC-0710] No ethernet interface on hardknott_5.10.72-2.2.0-stable

### ISSUE THREAD

**Issue by dbeulen** [TechNexion/meta-tn-imx-bsp#13]
When i compile with the hardknott_5.10.72-2.2.0-stable manifest ethernet does not work on the TC-0710 device. Upon boot it reports the following:
```

[  OK  ] Started Network Service.
[   12.318027] fec 2188000.ethernet eth0: no PHY, assuming direct connection to switch
[   12.325841] libphy: PHY fixed-0:00 not found
[   12.330191] fec 2188000.ethernet eth0: could not attach to PHY
[  OK  ] Started Connection service.
[   12.375735] fec 2188000.ethernet eth0: no PHY, assuming direct connection to switch
[   12.383478] libphy: PHY fixed-0:00 not found
[   12.387763] fec 2188000.ethernet eth0: could not attach to PHY
         Starting Avahi mDNS/DNS-SD Stack...
         Starting Hostname Service...
         Starting WPA supplicant...
[  OK  ] Started Avahi mDNS/DNS-SD Stack.
[  OK  ] Started Hostname Service.
[  OK  ] Started WPA supplicant.
[  OK  ] Reached target Network.
[  OK  ] Started Update psplash to network.
         Starting Terminate Psplash Boot Screen...
[  OK  ] Finished Terminate Psplash Boot Screen.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Finished Update UTMP about System Runlevel Changes.

TechNexion i.MX Release Distro 5.10-hardknott edm-imx6 ttymxc0

edm-imx6 login: 
```
if followed this guide https://developer.technexion.com/docs/building-an-image-with-yocto but updated my local.conf with these values as the sh file did not enter these values right in the configuration:
```
BASE_BOARD ?= "tc0700"
DISPLAY_INFO ?= "lvds7"
```
Full configuration file:
[local.conf.txt](https://github.com/TechNexion/meta-tn-imx-bsp/files/8949651/local.conf.txt)

If i plug in a cable i notice the green led blinking, orange led is off. On the default software the device worked, so it is not a hardware issue.

Part No. S600204020160480000441
Serial No. 22201154000022240001
Model name: TC0710PIMX6QR20E16

**Comment by richard-hu** [comment]
@dbeulen 

Thanks for the feedback !

I apologize for any inconvenience caused.
It's my fault. I neglect to update u-boot to latest version in [meta-tn-imx-bsp](https://github.com/TechNexion/meta-tn-imx-bsp).
To enable ethernet on TC0700, it should include the patch as follow:
https://github.com/TechNexion/u-boot-tn-imx/commit/8ae87966db41a82cdc51b3f72cb693d63de166ea

I just update u-boot/kernel recipe in  `meta-tn-imx-bsp` to point to latest u-boot and kernel. 
https://github.com/TechNexion/meta-tn-imx-bsp/commit/5934a6ac33e3b18c3baaddad1d395346351301f3

Could you give it a try to fetch `hardknott_5.10.72-2.2.0-next` instead of `hardknott_5.10.72-2.2.0-stable`?

$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-next -m imx-5.10.72-2.2.0.xml
$: repo sync -j8


BR,

Richard

**Comment by dbeulen** [comment]
Hello Richard,

I can confirm Ethernet works on the hardknott_5.10.72-2.2.0-next branch. 

Thank you for your help.
